# Generated by Django 4.0.2 on 2022-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('camera1', models.BooleanField(default=False)),
                ('camera2', models.BooleanField(default=False)),
                ('speed', models.FloatField(default=0.0)),
                ('averageSpeed', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('fuelLevel', models.FloatField(default=0.0)),
                ('engineStatus', models.FloatField(default=False)),
                ('staticMap', models.ImageField(upload_to='')),
            ],
        ),
    ]
