# Generated by Django 4.0.2 on 2022-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engineStatus',
            field=models.BooleanField(default=False),
        ),
    ]
