# Generated by Django 4.0.2 on 2022-02-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_enginestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='staticMap',
        ),
    ]
