# Generated by Django 4.0.2 on 2022-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_staticmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='staticMap',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
