# Generated by Django 4.0.2 on 2022-02-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_staticmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='staticMap',
        ),
    ]
