# Generated by Django 4.0.2 on 2022-02-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='maps',
        ),
    ]
