# Generated by Django 4.0.2 on 2022-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_remove_vehicle_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maps',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
